// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package api is a generated GoMock package.
package api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/sendlovebox/woocommerce-sdk/model"
)

// MockRemoteCalls is a mock of RemoteCalls interface.
type MockRemoteCalls struct {
	ctrl     *gomock.Controller
	recorder *MockRemoteCallsMockRecorder
}

// MockRemoteCallsMockRecorder is the mock recorder for MockRemoteCalls.
type MockRemoteCallsMockRecorder struct {
	mock *MockRemoteCalls
}

// NewMockRemoteCalls creates a new mock instance.
func NewMockRemoteCalls(ctrl *gomock.Controller) *MockRemoteCalls {
	mock := &MockRemoteCalls{ctrl: ctrl}
	mock.recorder = &MockRemoteCallsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRemoteCalls) EXPECT() *MockRemoteCallsMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockRemoteCalls) Auth(customerKey, customerSecret string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", customerKey, customerSecret)
	ret0, _ := ret[0].(error)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockRemoteCallsMockRecorder) Auth(customerKey, customerSecret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockRemoteCalls)(nil).Auth), customerKey, customerSecret)
}

// ListAllCategories mocks base method.
func (m *MockRemoteCalls) ListAllCategories(ctx context.Context, request model.SearchCategoriesRequest) ([]*model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllCategories", ctx, request)
	ret0, _ := ret[0].([]*model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllCategories indicates an expected call of ListAllCategories.
func (mr *MockRemoteCallsMockRecorder) ListAllCategories(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllCategories", reflect.TypeOf((*MockRemoteCalls)(nil).ListAllCategories), ctx, request)
}

// ListAllProducts mocks base method.
func (m *MockRemoteCalls) ListAllProducts(ctx context.Context, request model.SearchProductsRequest) ([]*model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllProducts", ctx, request)
	ret0, _ := ret[0].([]*model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllProducts indicates an expected call of ListAllProducts.
func (mr *MockRemoteCallsMockRecorder) ListAllProducts(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllProducts", reflect.TypeOf((*MockRemoteCalls)(nil).ListAllProducts), ctx, request)
}

// RetrieveACategory mocks base method.
func (m *MockRemoteCalls) RetrieveACategory(ctx context.Context, id string) (model.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveACategory", ctx, id)
	ret0, _ := ret[0].(model.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveACategory indicates an expected call of RetrieveACategory.
func (mr *MockRemoteCallsMockRecorder) RetrieveACategory(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveACategory", reflect.TypeOf((*MockRemoteCalls)(nil).RetrieveACategory), ctx, id)
}

// RetrieveAProduct mocks base method.
func (m *MockRemoteCalls) RetrieveAProduct(ctx context.Context, id string) (model.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetrieveAProduct", ctx, id)
	ret0, _ := ret[0].(model.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetrieveAProduct indicates an expected call of RetrieveAProduct.
func (mr *MockRemoteCallsMockRecorder) RetrieveAProduct(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetrieveAProduct", reflect.TypeOf((*MockRemoteCalls)(nil).RetrieveAProduct), ctx, id)
}

// RunInSandboxMode mocks base method.
func (m *MockRemoteCalls) RunInSandboxMode() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RunInSandboxMode")
}

// RunInSandboxMode indicates an expected call of RunInSandboxMode.
func (mr *MockRemoteCallsMockRecorder) RunInSandboxMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInSandboxMode", reflect.TypeOf((*MockRemoteCalls)(nil).RunInSandboxMode))
}
